"""empty message

Revision ID: 36e0b4c5b726
Revises: be38d26f54c9
Create Date: 2022-03-17 10:27:55.712684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36e0b4c5b726'
down_revision = 'be38d26f54c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('second_name', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('user_email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('user_pass', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['user_email'])
    op.drop_column('users', 'age')
    op.drop_column('users', 'address')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('address', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('age', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'user_pass')
    op.drop_column('users', 'user_email')
    op.drop_column('users', 'second_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
